### PR TITLE
fix: broken scraping methods

### PR DESCRIPTION
**Pull request by i0bs**

### CODE REVIEW

**Review by V3ntus — APPROVED** [review]
LGTM Thanks for contributing :D

**Comment by i0bs** [comment]
LGTM 👍🏼

**Comment by arHSM** [comment]
I will merge on one condition
- You will approve my idea

**Comment by i0bs** [comment]
no

**Comment by arHSM** [comment]
Ed i see you

**Comment by arHSM** [comment]
> no

ok nerd :p

**Pull request closed without merging**
